### ISSUE TITLE
Como levantar servidor XML Builder Signer con Java en Windows

### ISSUE THREAD

**Issue by cmb1197** [project-openubl/xml-builder#162]
Descargue PostgreSQL 12 y Release 1.0.0.Final del xml-builder.
Para ejecutar el jar utilizo el comando:

`java -Dquarkus.datasource.url=jdbc:postgresql://localhost:5432/ubl -Dquarkus.datasource.username=postgres -Dquarkus.datasource.password=1234 -Dquarkus.datasource.driver=org.postgresql.Driver -jar xml-builder-api-signer-1.0.0.Final-runner.jar`

Según la documentación para levantar la aplicacion  xml-builder-signer en un entorno de JVM de java las variables son: 
```
quarkus.datasource.url	
quarkus.datasource.driver	
quarkus.datasource.username	
quarkus.datasource.password
```

Al ejecutar el comando obtengo lo siguiente:

```
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-05-26 15:58:06,617 WARN  [io.agr.pool] (main) Datasource '<default>': Driver does not support the provided URL: jdbc:postgresql://localhost:5432/ubl
2020-05-26 15:58:06,630 WARN  [io.agr.pool] (Agroal_201905261) Datasource '<default>': Driver does not support the provided URL: jdbc:postgresql://localhost:5432/ubl
2020-05-26 15:58:06,631 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) SQL Error: 0, SQLState: null
2020-05-26 15:58:06,631 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) Driver does not support the provided URL: jdbc:postgresql://localhost:5432/ubl
2020-05-26 15:58:06,642 ERROR [io.qua.application] (main) Failed to start application: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:110)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:70)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:54)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:110)
        at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:58)
        at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:82)
        at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits163.deploy_0(HibernateOrmProcessor$startPersistenceUnits163.zig:70)
        at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits163.deploy(HibernateOrmProcessor$startPersistenceUnits163.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:175)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.Application.run(Application.java:228)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: org.hibernate.exception.GenericJDBCException: Unable to open JDBC Connection for DDL execution
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.resource.transaction.backend.jta.internal.DdlTransactionIsolatorJtaImpl.<init>(DdlTransactionIsolatorJtaImpl.java:62)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorBuilderImpl.buildDdlTransactionIsolator(JtaTransactionCoordinatorBuilderImpl.java:46)
        at org.hibernate.tool.schema.internal.HibernateSchemaManagementTool.getDdlTransactionIsolator(HibernateSchemaManagementTool.java:175)
        at org.hibernate.tool.schema.internal.HibernateSchemaManagementTool.buildGenerationTargets(HibernateSchemaManagementTool.java:135)
        at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:110)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:145)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:314)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:68)
        ... 12 more
Caused by: java.sql.SQLException: Driver does not support the provided URL: jdbc:postgresql://localhost:5432/ubl
        at io.agroal.pool.ConnectionFactory.connectionSetup(ConnectionFactory.java:215)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:200)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:390)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:372)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:261)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.Application.run(Application.java:228)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:110)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:70)
        at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:54)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:110)
        at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:58)
        at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:82)
        at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits163.deploy_0(HibernateOrmProcessor$startPersistenceUnits163.zig:70)
        at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits163.deploy(HibernateOrmProcessor$startPersistenceUnits163.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:175)
        ... 3 more
Caused by: org.hibernate.exception.GenericJDBCException: Unable to open JDBC Connection for DDL execution
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.resource.transaction.backend.jta.internal.DdlTransactionIsolatorJtaImpl.<init>(DdlTransactionIsolatorJtaImpl.java:62)
        at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorBuilderImpl.buildDdlTransactionIsolator(JtaTransactionCoordinatorBuilderImpl.java:46)
        at org.hibernate.tool.schema.internal.HibernateSchemaManagementTool.getDdlTransactionIsolator(HibernateSchemaManagementTool.java:175)
        at org.hibernate.tool.schema.internal.HibernateSchemaManagementTool.buildGenerationTargets(HibernateSchemaManagementTool.java:135)
        at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:110)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:145)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:314)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:68)
        ... 12 more
Caused by: java.sql.SQLException: Driver does not support the provided URL: jdbc:postgresql://localhost:5432/ubl
        at io.agroal.pool.ConnectionFactory.connectionSetup(ConnectionFactory.java:215)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:200)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:390)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:372)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
2020-05-26 15:58:07,307 WARN  [io.qua.net.run.NettyRecorder] (Thread-2) Localhost lookup took more than one second, you need to add a /etc/hosts entry to improve Quarkus startup time. On Windows the path is C:\Windows\System32\Drivers\etc\hosts. See https://thoeni.io/post/macos-sierra-java/ for macOS details.
```

**Comment by carlosthe19916** [comment]
@cmb1197 podrías darme algún comando (por ejemplo docker) que me permita reproducir tu version de Postgresql?

Por otro lado, el código para generar firmas digitales y guardarlas en una base de datos `xml-signer` está siendo movida a https://github.com/project-openubl/openubl. En la siguiente version de `xml-builder (1.1.0.Final)` la firma es opcional pero si se desea firmar un comprobante entonces hay dos caminos:
1. Enviar las llaves en los headers de las peticiones HTTP. Ejemplo https://github.com/project-openubl/xml-builder/blob/8b86b84bb0ed134b40a2fa598ee4cc0ef36456aa/api/src/test/java/io/github/project/openubl/xmlbuilder/resources/DocumentsResourceTest.java#L423

2. Levantar el servidor con dos propiedades `openubl.server.keystore.location` y `openubl.server.keystore.password` apuntando a tu certificado digital, de este modo todos tus comprobantes serán firmados con un solo certificado digital.

Ejemplo para windows (descarga el ejecutable desde https://github.com/project-openubl/xml-builder/releases/tag/1.1.0.RC1):

Paso1 configura tus variables de entorno o simplemente en el terminal ejecutar:
```
set OPENUBL_SERVER_KEYSTORE_PASSWORD=password
set OPENUBL_SERVER_KEYSTORE_LOCATION=C:\\Users\\cferiavi\\Downloads\\xml-builder-master\\api\\src\\test\\resources\\LLAMA-PE-CERTIFICADO-DEMO-10467793549.pfx
```
Paso2 inicia el servidor ejecutando en el terminal:
```
xml-builder-api-1.1.0.RC1-runner.exe
```

La documentación no está actualizada ya que no cuento con mucho tiempo para mejorar el codigo y actualizar la documentación a la misma vez. Te recomiendo actualizar tu versión a la última version.

Me podrías decir que es lo que buscas lograr con tu software? si deseas podemos pactar una reunion breve de 15 minutes y te explico que hace y que no hace `XML Builder` cosa que puedes tomar buenas decisiones con tu software

**Comment by cmb1197** [comment]
Gracias por responder, mi problema era que tengo una aplicación en .NET que se comunica con el xml-builder y las pruebas con el xml-builder-signer las hice con Docker como menciona en la documentación. Todo funcionaba normal en las pruebas, las organizaciones no se borraban si dejaba de correr el xml-builder-signer, hasta donde entendí son 2 contenedores y uno de ellos tiene una base de datos PosgreSQL.

Pero cuando hice las pruebas en el servidor del negocio este no podía utilizar Linux Containers con Docker por que el SO es Windows Server 2016 versión 1607 (según lo que leí Linux Containers con Docker funciona con la versión 1709 en adelante) así que la única opción que vi fue correrlo con Java con el comando:

`java -jar xml-builder-api-signer-1.0.0.Final-runner.jar`

Al utilizar ese comando si creaba una organización mediante la consola de administración del openUBL esta se borraba si la ejecución del jar se detenía.
Pensé que si instalaba PostgreSQL en el servidor y apuntaba a ese motor de base de datos con las variables de entorno el xml-builder-signer utilizaría la base de datos PostgreSQL. Pero el resultado fue el error que mencione antes.

Lo pude solucionar bajando el código fuente de la versión 1.0.0.Final y haciendo build otra vez pero con el profile postgres.

Instale Maven y Java jkd 8.
Como dice la documentación, en la carpeta del proyecto:
`mvnw install -DskipTests`

Y este comando lo vi en el archivo Dockerfile.apisigner.multistage que esta en la carpeta del proyecto.
`C:/Users/Carlos/Desktop/xml-builder-1.0.0.Final/mvnw -f C:/Users/Carlos/Desktop/xml-builder-1.0.0.Final/pom.xml -P ui -Dquarkus.profile=postgresql -DskipTests clean package`
